"use client"

import React, { useEffect, useState } from 'react';
import KPIMetrics from '@/components/dashboard/KPIMetrics';
import TransactionTrends from '@/components/dashboard/TransactionTrends';
import ModelPerformance from '@/components/dashboard/ModelPerformance';
import RecentAlerts from '@/components/dashboard/RecentAlerts';
import TransactionTester from '@/components/dashboard/TransactionTester';
import FeatureImportance from '@/components/dashboard/FeatureImportance';
import QuantumState from '@/components/dashboard/QuantumState';
import FederatedLearning from '@/components/dashboard/FederatedLearning';
import GraphNetwork from '@/components/dashboard/GraphNetwork';

export default function Dashboard() {
  const [data, setData] = useState<any>(null);
  
  useEffect(() => {
    // Generate dynamic dates for realistic ML project feel
    const today = new Date();
    const formatDate = (d: Date) => d.toISOString().split('T')[0];
    const formatTime = (d: Date) => d.toISOString();
    
    setTimeout(() => {
      setData({
        transactions_processed: 15847,
        fraud_detected: 267,
        fraud_rate: 1.68,
        avg_processing_time_ms: 45.2,
        model_accuracy: 99.87,
        daily_stats: Array.from({length: 7}).map((_, i) => {
          const d = new Date(today);
          d.setDate(d.getDate() - (6 - i));
          return {
            date: formatDate(d),
            transactions: 2000 + Math.floor(Math.random() * 500),
            fraud: 20 + Math.floor(Math.random() * 30)
          };
        }),
        model_performance: {
          xgboost_v2: { accuracy: 99.89, precision: 98.5, recall: 96.8, f1_score: 97.6, auc_roc: 0.991, inference_ms: 12.4 },
          lightgbm_v4: { accuracy: 99.85, precision: 98.2, recall: 96.9, f1_score: 97.5, auc_roc: 0.989, inference_ms: 8.7 },
          catboost_v1: { accuracy: 99.82, precision: 97.9, recall: 97.1, f1_score: 97.5, auc_roc: 0.985, inference_ms: 15.2 }
        },
        feature_importance: [
          { feature: 'V14', importance: 0.24, description: 'PCA Component 14' },
          { feature: 'V4', importance: 0.18, description: 'PCA Component 4' },
          { feature: 'V12', importance: 0.15, description: 'PCA Component 12' },
          { feature: 'Amount', importance: 0.11, description: 'Transaction Amount' },
          { feature: 'V17', importance: 0.08, description: 'PCA Component 17' },
        ],
        recent_alerts: [
          { id: `TXN-${Math.floor(Math.random()*10000)}`, amount: 15000, risk_score: 95.2, timestamp: formatTime(new Date(today.getTime() - 15 * 60000)) },
          { id: `TXN-${Math.floor(Math.random()*10000)}`, amount: 8500, risk_score: 88.7, timestamp: formatTime(new Date(today.getTime() - 45 * 60000)) },
          { id: `TXN-${Math.floor(Math.random()*10000)}`, amount: 12000, risk_score: 92.1, timestamp: formatTime(new Date(today.getTime() - 120 * 60000)) },
          { id: `TXN-${Math.floor(Math.random()*10000)}`, amount: 450, risk_score: 75.4, timestamp: formatTime(new Date(today.getTime() - 150 * 60000)) },
        ]
      });
    }, 500);
  }, []);

  return (
    <div className="w-full">
      {/* Notion style header */}
      <div className="mb-8 group">
        <div className="text-6xl mb-4">🛡️</div>
        <h1 className="text-4xl font-bold mb-2 tracking-tight">Fraud Detection Dashboard</h1>
        <div className="flex items-center gap-4 text-sm text-[var(--text-muted)] border-b border-[var(--border-color)] pb-4">
          <span>Updated just now</span>
          <span>•</span>
          <span>Real-time analytics active</span>
        </div>
      </div>

      <div className="space-y-12">
        <section>
          <KPIMetrics data={data} />
        </section>
        
        <section className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <div className="lg:col-span-2">
            <TransactionTrends data={data?.daily_stats} />
          </div>
          <div>
            <RecentAlerts alerts={data?.recent_alerts} />
          </div>
        </section>

        <section className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          <ModelPerformance data={data?.model_performance} />
          <FeatureImportance data={data?.feature_importance} />
        </section>

        {/* AI & Quantum Insights Section */}
        <section className="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-8">
          <div className="lg:col-span-2 notion-card p-6 border-l-4 border-l-[var(--highlight)]">
            <h3 className="text-lg font-semibold mb-2 flex items-center gap-2">✨ AI Fraud Analyst Insights</h3>
            <p className="text-sm text-[var(--text-muted)] mb-4">Generated by Gemini Pro via LLM Inference</p>
            <div className="space-y-3 text-sm">
              <p>• <strong>Anomaly Detected:</strong> Transaction clustering in the EU region has shown a 12% drift from baseline over the last 24 hours.</p>
              <p>• <strong>Feature Shift:</strong> PCA Component 14 (V14) importance has spiked, correlating strongly with high-velocity micro-transactions.</p>
              <p>• <strong>Recommendation:</strong> Retrain the LightGBM ensemble on the latest 48-hour window to compensate for the detected data drift.</p>
            </div>
          </div>
          
          <QuantumState />
        </section>

        {/* Distributed ML Section */}
        <section className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-8">
          <FederatedLearning />
          <GraphNetwork />
        </section>

        <section>
          <TransactionTester />
        </section>
      </div>
    </div>
  );
}
